"""Shared constants for the feedback pipeline."""

CHUNK_TEXT_MAX_CHARS = 500
EXPLANATION_MAX_CHARS = 1500
MISCONCEPTION_MAX_CHARS = 600
TIP_MAX_CHARS = 300
EVALUATION_SUMMARY_MAX_CHARS = 400
STUDY_SUGGESTION_MAX_CHARS = 600
STUDENT_FEEDBACK_MAX_CHARS = 800
WHY_WRONG_MAX_CHARS = 600

# Prompt versioning
FEEDBACK_PROMPT_VERSION = "physics-feedback-v2"

# Regeneration
MAX_FEEDBACK_REGENERATION_ATTEMPTS = 2
